### ISSUE TITLE
Vite v5 support

### ISSUE THREAD

**Issue by klasjersevi** [redfox-mx/vite-lit-css#2]
This looks so promising, but unfortunately it wasn't compatible with Vite v5.2.10, which I'm currently using.

Is there a possibility to add Vite v5 support?

Thanks,
Klas

**Comment by delaneyj** [comment]
I'm running into the same issue

**Comment by redfox-mx** [comment]
Hi! Thanks, unfortunately vite default export for styles has been removed and I need to rewrite some patches since internal apis now works a little bit different. I mean, sounds easy but it's needs a lot of research into vite source code n.n' 

So maybe I need more time to get it works :c but please, be patient ❤️

**Comment by delaneyj** [comment]
Thanks for the update, for now I moved back to vite4 as your project is wonderful for fast track development tailwindcss/daisyui with lit.  Look forward to an update when you have time!  Using for a time travelling inspector for https://data-star.dev

**Comment by redfox-mx** [comment]
Hi @delaneyj, @klasjersevi 

I have been working on updates for vite 5, could you test [2.0.0-vite.5](https://www.npmjs.com/package/vite-plugin-lit-css/v/2.0.0-vite.5)?

I drop support for css modules and if you have stylesheets imported in your index.html must be setted inside exclude option to get it works

**Comment by klasjersevi** [comment]
> Hi @delaneyj, @klasjersevi
> 
> I have been working on updates for vite 5, could you test [2.0.0-vite.5](https://www.npmjs.com/package/vite-plugin-lit-css/v/2.0.0-vite.5) version?
> 
> I drop support for css modules and if you have stylesheets imported in your index.html must be setted inside exclude option to get it works

I've tested it in my vite 5 project now and it seems to work fine! 👍 I couldn't find any issues.
